export const ourServices = [
    {
      id: 1,
      title: "Software Development",
      imagesrc: "/assets/services/SoftDev/SoftDev2.jpeg",
      description: "We deliver innovative software tailored to your business needs. Trust us for reliable, high-quality development that ensures your success.",
      href1: "/services/softwareDevelopment",
    },
    {
      id: 2,
      title: "Artificial Intelligence And ML",
      imagesrc: "/assets/services/aiML/Robo.jpg",
      description: "Harness the power of AI and ML to transform your business operations. Our advanced solutions drive innovation, setting you ahead of the competition.",
      href1: "/services/aiAndml",
    },
    {
      id: 3,
      title: "Salesforce Services",
      imagesrc: "/assets/services/salesforce/slaewave.jpeg",
      description: "Optimize your customer relationship management with our Salesforce services. We provide tailored solutions to streamline your processes and boost your efficiency.",
      href1: "/services/salesforce",
    },
    {
      id: 4,
      title: "BI And Analytics",
      imagesrc: "/assets/services/BIdataAnalytics/bi.jpg",
      description: "We provide comprehensive BI and analytics solutions tailored to your business needs, empowering data-driven decision-making for growth and efficiency.",
      href1: "/services/BIandAnalytics",
    },
    {
      id: 5,
      title: "Software Testing And QA",
      imagesrc: "/assets/services/TestingandQA/commitment.jpg",
      description: "We guarantee flawless software performance with our rigorous testing and quality assurance services ensuring a seamless launch for your product.",
      href1: "/services/TestingandQA",
    },
    {
      id: 6,
      title: "Devops",
      imagesrc: "/assets/services/DevOps/DevOps.jpeg",
      description: "Streamline development and operations with our DevOps expertise. We optimize workflows, automate processes and ensure faster, efficient software delivery.",
      href1: "/services/devOps",
    },
    {
      id: 7,
      title: "Cloud Computing",
      imagesrc: "/assets/services/CloudComputing/Cloud1.jpg",
      description: "Unlock scalable infrastructure with our cloud computing solutions. Seamlessly transition for enhanced reliability, security, and efficiency in operations.",
      href1: "/services/cloudComputing",
    },
    {
      id: 8,
      title: "Web Development",
      imagesrc: "/assets/services/webDev/webdev.jpg",
      description: "Craft captivating online experiences tailored to your brand with our expert web development services, bringing your digital vision to life with precision and creativity.",
      href1: "/services/WebDevelopment",
    },
    {
      id: 9,
      title: "Digital Marketing",
      imagesrc: "/assets/services/digitalMarketing/sectwo.jpg",
      description: "Boost your online presence with our strategic solutions. From SEO to social media, we optimize your digital strategy for maximum impact and growth.",
      href1: "/services/digitalMarketing",

    },
    {
      id: 10,
      title: "Cyber Security",
      imagesrc: "/assets/services/CyberSecurity/cs1.jpg",
      description: "We provide comprehensive cybersecurity services, protecting your data, networks and systems from threats, ensuring confidentiality, integrity and availability.",
      href1: "/services/CyberSecurity",

    },
    {
      id: 11,
      title: "Big Data Analytics",
      imagesrc: "/assets/services/BigDataAnalytics/bigdata.jpg",
      description: "Empower data-driven decisions with our advanced BI and analytics solutions. Gain valuable insights to drive your business forward with confidence and precision.",
      href1: "/services/BigDataAnalytics",

    },
    {
      id: 12,
      title: "Product Devlopement",
      imagesrc: "/assets/services/ProductDevelopment/expertise.jpg",
      description: "We specialize in product development, leveraging cutting-edge technologies and agile methodologies to bring your ideas to life efficiently and innovatively.",
      href1: "/services/ProductDevelopment",
    },
    {
      id: 13,
      title: "CRM Services",
      imagesrc: "/assets/services/Crm/CRM1.jpg",
      description: "Enhance customer satisfaction with tailored CRM solutions. Streamline processes and nurture relationships for sustained growth.",
      href1: "/services/crm",
    },
    {
      id: 14,
      title: "IT Staffing",
      imagesrc: "/assets/services/ItStaffing/Staffing2.jpg",
      description: "Unlock your team's potential with our specialized IT staffing solutions. From talent acquisition to onboarding, we ensure a perfect fit for your success.",
      href1: "/services/staffing",

    },
    {
      id: 15,
      title: "IT Service Support",
      imagesrc: "/assets/services/ITServiceSupport/helpdesksupport.jpg",
      description: "Rely on our expert IT support for seamless operations. From troubleshooting to proactive maintenance, we keep your systems running smoothly, letting focus.",
      href1: "/services/ITServiceSupport",
    },
  ];