export const ourServices = [
    {
      id: 1,
      title: "Software Development",
      imagesrc: "/assets/services/ChardsPhoto/SoftwareDev.jpg",
      description: "We deliver innovative software tailored to your business needs. Trust us for reliable, high-quality development that ensures your success.",
      href1: "/services/softwareDevelopment",
    },
    {
      id: 2,
      title: "Artificial Intelligence and ML",
      imagesrc: "/assets/services/ChardsPhoto/Ai.jpg",
      description: "Harness the power of AI and ML to transform your business operations. Our advanced solutions drive innovation and efficiency, setting you ahead of the competition.",
      href1: "/services/aiAndml",
    },
    {
      id: 3,
      title: "Salesforce Services",
      imagesrc: "/assets/services/ChardsPhoto/SSalesforce.jpg",
      description: "Optimize your customer relationship management with our expert Salesforce services. We provide tailored solutions to streamline your processes and boost your business efficiency.s",
      href1: "/services/salesforce",
    },
    {
      id: 4,
      title: "BI and Analytics",
      imagesrc: "/assets/services/ChardsPhoto/BIAnalytics.jpg",
      description: "We provide comprehensive BI and analytics solutions tailored to your business needs, empowering data-driven decision-making for growth and efficiency.",
      href1: "/services/BIandAnalytics",
    },
    {
      id: 5,
      title: "Software Testing and QA",
      imagesrc: "/assets/services/ChardsPhoto/testing.jpg",
      description: "We guarantee flawless software performance with our rigorous testing and quality assurance services ensuring a seamless launch for your product.",
      href1: "/services/TestingandQA",
    },
    {
      id: 6,
      title: "Devops",
      imagesrc: "/assets/services/ChardsPhoto/devops1.jpg",
      description: "Streamline your development and operations with our DevOps expertise. We optimize workflows, automate processes and ensure seamless collaboration for faster, more efficient software delivery.",
      href1: "/services/devOps",
    },
    {
      id: 7,
      title: "Cloud Computing",
      imagesrc: "/assets/services/ChardsPhoto/cloudcomputing.jpg",
      description: "Unlock the power of scalable, flexible infrastructure with our cloud computing solutions. Seamlessly transition to the cloud for enhanced reliability, security and efficiency in your operations.",
      href1: "/services/cloudComputing",
    },
    {
      id: 8,
      title: "Web Site Development",
      imagesrc: "/assets/services/ChardsPhoto/webdev.jpg",
      description: "Craft captivating online experiences tailored to your brand with our expert website development services. From sleek designs to seamless functionality, we bring your digital vision to life with precision and creativity.",
      href1: "/services/WebDevelopment",
    },
    {
      id: 9,
      title: "Digital Marketing",
      imagesrc: "/assets/services/ChardsPhoto/digitalMarket.jpg",
      description: "Boost your online presence with our strategic solutions. From SEO to social media, we optimize your digital strategy for maximum impact and growth.",
      href1: "/services/digitalMarketing",

    },
    {
      id: 10,
      title: "Cyber Security",
      imagesrc: "/assets/services/ChardsPhoto/cyberSequ.jpg",
      description: "We provide comprehensive cybersecurity services, protecting your data, networks and systems from threats, ensuring confidentiality, integrity and availability.",
      href1: "/services/CyberSecurity",

    },
    {
      id: 11,
      title: "Big Data Analytics",
      imagesrc: "/assets/services/ChardsPhoto/BiV.jpg",
      description: "Empower data-driven decisions with our advanced BI and analytics solutions. Gain valuable insights to drive your business forward with confidence and precision.",
      href1: "/services/BigDataAnalytics",

    },
    {
      id: 12,
      title: "Product Devlopement",
      imagesrc: "/assets/services/ChardsPhoto/Product.jpg",
      description: "We specialize in product development, leveraging cutting-edge technologies and agile methodologies to bring your ideas to life efficiently and innovatively.",
      href1: "/services/ProductDevelopment",
    },
    {
      id: 13,
      title: "CRM Services",
      imagesrc: "/assets/services/ChardsPhoto/CRM.jpg",
      description: "Optimize interactions and enhance customer satisfaction with our tailored CRM solutions. Streamline processes and nurture relationships for sustained business growth.",
      href1: "/services/crm",
    },
    {
      id: 14,
      title: "IT Staffing",
      imagesrc: "/assets/services/ChardsPhoto/ItStaff.jpg",
      description: "Unlock your team's full potential with our specialized IT staffing solutions. From top-tier talent acquisition to seamless onboarding, we ensure a perfect fit for your organization's success.",
      href1: "/services/staffing",

    },
    {
      id: 15,
      title: "IT Service Support",
      imagesrc: "/assets/services/ChardsPhoto/IT-Suppjpg.jpg",
      description: "Rely on our expert IT support for seamless operations. From troubleshooting to proactive maintenance, we keep your systems running smoothly, so you can focus on your business.",
      href1: "/services/ITServiceSupport",
    },
  ];